### ISSUE TITLE
NOT RELEASING RESOURCES

### ISSUE THREAD

**Issue by xocasdashdash** [richo/GOSHOUT#3]
ONCE YOU READ THE BODY ON https://github.com/richo/GOSHOUT/blob/master/SHOUT.go#L35 YOU'RE NOT CALLING CLOSE ON IT. SEE HERE FOR MORE DETAILS https://github.com/golang/go/issues/14942 THANK YOU

**Comment by richo** [comment]
I believe this is fixed by https://github.com/richo/GOSHOUT/pull/4

**Comment by xocasdashdash** [comment]
THANK YOU!
